# load up the model of Apple
apple_data = [
    {"modelValue": "iPad Pro 12.9 (2022)"},
    {"modelValue": "iPad Pro 11 (2022)"},
    {"modelValue": "iPad (2022)"},
    {"modelValue": "iPhone 14 Pro Max"},
    {"modelValue": "iPhone 14 Pro"},
    {"modelValue": "iPhone 14 Plus"},
    {"modelValue": "iPhone 14"},
    {"modelValue": "Watch Ultra"},
    {"modelValue": "Watch Series 8"},
    {"modelValue": "Watch Series 8 Aluminum"},
    {"modelValue": "Watch SE (2022)"},
    {"modelValue": "iPhone SE (2022)"},
    {"modelValue": "iPad Air (2022)"},
    {"modelValue": "iPhone 13 Pro Max"},
    {"modelValue": "iPhone 13 Pro"},
    {"modelValue": "iPhone 13"},
    {"modelValue": "iPhone 13 mini"},
    {"modelValue": "iPad mini (2021)"},
    {"modelValue": "iPad 10.2 (2021)"},
    {"modelValue": "Watch Edition Series 7"},
    {"modelValue": "Watch Series 7"},
    {"modelValue": "Watch Series 7 Aluminum"},
    {"modelValue": "iPad Pro 12.9 (2021)"},
    {"modelValue": "iPad Pro 11 (2021)"},
    {"modelValue": "iPhone 12 Pro Max"},
    {"modelValue": "iPhone 12 Pro"},
    {"modelValue": "iPhone 12"},
    {"modelValue": "iPhone 12 mini"},
    {"modelValue": "iPad Air (2020)"},
    {"modelValue": "iPad 10.2 (2020)"},
    {"modelValue": "Watch SE"},
    {"modelValue": "Watch Series 6 Aluminum"},
    {"modelValue": "Watch Series 6"},
    {"modelValue": "Watch Edition Series 6"},
    {"modelValue": "iPhone SE (2020)"},
    {"modelValue": "iPad Pro 12.9 (2020)"},
    {"modelValue": "iPad Pro 11 (2020)"},
    {"modelValue": "iPhone 11 Pro Max"},
    {"modelValue": "iPhone 11 Pro"},
    {"modelValue": "iPhone 11"},
    {"modelValue": "iPad 10.2 (2019)"},
    {"modelValue": "Watch Edition Series 5"},
    {"modelValue": "Watch Series 5"},
    {"modelValue": "Watch Series 5 Aluminum"},
    {"modelValue": "iPad Air (2019)"},
    {"modelValue": "iPad mini (2019)"},
    {"modelValue": "iPad Pro 12.9 (2018)"},
    {"modelValue": "iPad Pro 11 (2018)"},
    {"modelValue": "iPhone XS Max"},
    {"modelValue": "iPhone XS"},
    {"modelValue": "iPhone XR"},
    {"modelValue": "Watch Series 4"},
    {"modelValue": "Watch Series 4 Aluminum"},
    {"modelValue": "iPad 9.7 (2018)"},
    {"modelValue": "iPhone X"},
    {"modelValue": "iPhone 8 Plus"},
    {"modelValue": "iPhone 8"},
    {"modelValue": "Watch Edition Series 3"},
    {"modelValue": "Watch Series 3"},
    {"modelValue": "Watch Series 3 Aluminum"},
    {"modelValue": "iPad Pro 12.9 (2017)"},
    {"modelValue": "iPad Pro 10.5 (2017)"},
    {"modelValue": "iPad 9.7 (2017)"},
    {"modelValue": "Watch Edition Series 2 42mm"},
    {"modelValue": "Watch Edition Series 2 38mm"},
    {"modelValue": "Watch Series 2 42mm"},
    {"modelValue": "Watch Series 2 38mm"},
    {"modelValue": "Watch Series 2 Aluminum 42mm"},
    {"modelValue": "Watch Series 1 Aluminum 42mm"},
    {"modelValue": "Watch Series 2 Aluminum 38mm"},
    {"modelValue": "Watch Series 1 Aluminum 38mm"},
    {"modelValue": "iPhone 7 Plus"},
    {"modelValue": "iPhone 7"},
    {"modelValue": "iPad Pro 9.7 (2016)"},
    {"modelValue": "iPhone SE"},
    {"modelValue": "iPhone 6s Plus"},
    {"modelValue": "iPhone 6s"},
    {"modelValue": "iPad Pro 12.9 (2015)"},
    {"modelValue": "iPad mini 4 (2015)"},
    {"modelValue": "Watch Edition 42mm (1st gen)"},
    {"modelValue": "Watch Edition 38mm (1st gen)"},
    {"modelValue": "Watch 42mm (1st gen)"},
    {"modelValue": "Watch 38mm (1st gen)"},
    {"modelValue": "Watch Sport 42mm (1st gen)"},
    {"modelValue": "Watch Sport 38mm (1st gen)"},
    {"modelValue": "iPad Air 2"},
    {"modelValue": "iPad mini 3"},
    {"modelValue": "iPhone 6 Plus"},
    {"modelValue": "iPhone 6"},
    {"modelValue": "iPad Air"},
    {"modelValue": "iPad mini 2"},
    {"modelValue": "iPhone 5s"},
    {"modelValue": "iPhone 5c"},
    {"modelValue": "iPad mini Wi-Fi"},
    {"modelValue": "iPad mini Wi-Fi + Cellular"},
    {"modelValue": "iPad 4 Wi-Fi"},
    {"modelValue": "iPad 4 Wi-Fi + Cellular"},
    {"modelValue": "iPhone 5"},
    {"modelValue": "iPad 3 Wi-Fi + Cellular"},
    {"modelValue": "iPad 3 Wi-Fi"},
    {"modelValue": "iPhone 4s"},
    {"modelValue": "iPad 2 Wi-Fi + 3G"},
    {"modelValue": "iPad 2 Wi-Fi"},
    {"modelValue": "iPad 2 CDMA"},
    {"modelValue": "iPhone 4"},
    {"modelValue": "iPhone 4 CDMA"},
    {"modelValue": "iPad Wi-Fi + 3G"},
    {"modelValue": "iPad Wi-Fi"},
    {"modelValue": "iPhone 3GS"},
    {"modelValue": "iPhone 3G"},
    {"modelValue": "iPhone"},
]


# tecno_data

# huaweie_data

# nokia_data


# load up modedl for Samsung
samsung_data = [
    {"modelValue": "Galaxy M04"},
    {"modelValue": "Galaxy Tab A7 10.4 (2022)"},
    {"modelValue": "Galaxy A04e"},
    {"modelValue": "Galaxy Tab Active4 Pro"},
    {"modelValue": "Galaxy A04s"},
    {"modelValue": "Galaxy A04"},
    {"modelValue": "Galaxy Z Fold4"},
    {"modelValue": "Galaxy Z Flip4"},
    {"modelValue": "Galaxy Watch5 Pro"},
    {"modelValue": "Galaxy Watch5"},
    {"modelValue": "Galaxy A23 5G"},
    {"modelValue": "Galaxy M13 5G"},
    {"modelValue": "Galaxy M13 (India)"},
    {"modelValue": "Galaxy A13 (SM-A137)"},
    {"modelValue": "Galaxy Xcover6 Pro"},
    {"modelValue": "Galaxy F13"},
    {"modelValue": "Galaxy M13"},
    {"modelValue": "Galaxy Tab S6 Lite (2022)"},
    {"modelValue": "Galaxy M53"},
    {"modelValue": "Galaxy S20 FE 2022"},
    {"modelValue": "Galaxy A73 5G"},
    {"modelValue": "Galaxy A53 5G"},
    {"modelValue": "Galaxy A33 5G"},
    {"modelValue": "Galaxy F23"},
    {"modelValue": "Galaxy M33"},
    {"modelValue": "Galaxy M23"},
    {"modelValue": "Galaxy A23"},
    {"modelValue": "Galaxy A13"},
    {"modelValue": "Galaxy S22 Ultra 5G"},
    {"modelValue": "Galaxy S22+ 5G"},
    {"modelValue": "Galaxy S22 5G"},
    {"modelValue": "Galaxy Tab S8 Ultra"},
    {"modelValue": "Galaxy Tab S8+"},
    {"modelValue": "Galaxy Tab S8"},
    {"modelValue": "Galaxy S21 FE 5G"},
    {"modelValue": "Galaxy Tab A8 10.5 (2021)"},
    {"modelValue": "Galaxy A13 5G"},
    {"modelValue": "Galaxy A03"},
    {"modelValue": "Galaxy A03 Core"},
    {"modelValue": "Galaxy F42 5G"},
    {"modelValue": "Galaxy M52 5G"},
    {"modelValue": "Galaxy M22"},
    {"modelValue": "Galaxy M32 5G"},
    {"modelValue": "Galaxy A03s"},
    {"modelValue": "Galaxy A52s 5G"},
    {"modelValue": "Galaxy Z Fold3 5G"},
    {"modelValue": "Galaxy Z Flip3 5G"},
    {"modelValue": "Galaxy Watch4 Classic"},
    {"modelValue": "Galaxy Watch4"},
    {"modelValue": "Galaxy A12 (India)"},
    {"modelValue": "Galaxy A12 Nacho"},
    {"modelValue": "Galaxy M21 2021"},
    {"modelValue": "Galaxy F22"},
    {"modelValue": "Galaxy M32"},
    {"modelValue": "Galaxy A22 5G"},
    {"modelValue": "Galaxy A22"},
    {"modelValue": "Galaxy Tab A7 Lite"},
    {"modelValue": "Galaxy Tab S7 FE"},
    {"modelValue": "Galaxy F52 5G"},
    {"modelValue": "Galaxy M42 5G"},
    {"modelValue": "Galaxy M12"},
    {"modelValue": "Galaxy Quantum 2"},
    {"modelValue": "Galaxy F12"},
    {"modelValue": "Galaxy F02s"},
    {"modelValue": "Galaxy A72"},
    {"modelValue": "Galaxy A52 5G"},
    {"modelValue": "Galaxy A52"},
    {"modelValue": "Galaxy Xcover 5"},
    {"modelValue": "Galaxy A32"},
    {"modelValue": "Galaxy M62"},
    {"modelValue": "Galaxy F62"},
    {"modelValue": "Galaxy M12 (India)"},
    {"modelValue": "Galaxy S21 Ultra 5G"},
    {"modelValue": "Galaxy S21+ 5G"},
    {"modelValue": "Galaxy S21 5G"},
    {"modelValue": "Galaxy A32 5G"},
    {"modelValue": "Galaxy M02s"},
    {"modelValue": "Galaxy A12"},
    {"modelValue": "Galaxy M02"},
    {"modelValue": "Galaxy A02"},
    {"modelValue": "Galaxy A02s"},
    {"modelValue": "Galaxy M21s"},
    {"modelValue": "Galaxy M31 Prime"},
    {"modelValue": "Galaxy F41"},
    {"modelValue": "Galaxy Tab Active3"},
    {"modelValue": "Galaxy S20 FE 5G"},
    {"modelValue": "Galaxy S20 FE"},
    {"modelValue": "Galaxy A42 5G"},
    {"modelValue": "Galaxy Tab A7 10.4 (2020)"},
    {"modelValue": "Galaxy M51"},
    {"modelValue": "Galaxy A51 5G UW"},
    {"modelValue": "Galaxy Z Fold2 5G"},
    {"modelValue": "Galaxy Note20 Ultra 5G"},
    {"modelValue": "Galaxy Note20 Ultra"},
    {"modelValue": "Galaxy Note20 5G"},
    {"modelValue": "Galaxy Note20"},
    {"modelValue": "Galaxy Watch3"},
    {"modelValue": "Galaxy Tab S7+"},
    {"modelValue": "Galaxy Tab S7"},
    {"modelValue": "Galaxy Z Flip 5G"},
    {"modelValue": "Galaxy M31s"},
    {"modelValue": "Galaxy M01s"},
    {"modelValue": "Galaxy M01 Core"},
    {"modelValue": "Galaxy A01 Core"},
    {"modelValue": "Galaxy A71 5G UW"},
    {"modelValue": "Galaxy M01"},
    {"modelValue": "Galaxy A21s"},
    {"modelValue": "Galaxy J2 Core (2020)"},
    {"modelValue": "Galaxy A Quantum"},
    {"modelValue": "Galaxy A71 5G"},
    {"modelValue": "Galaxy A51 5G"},
    {"modelValue": "Galaxy A21"},
    {"modelValue": "Galaxy Tab A 8.4 (2020)"},
    {"modelValue": "Galaxy Tab S6 Lite"},
    {"modelValue": "Galaxy M11"},
    {"modelValue": "Galaxy A31"},
    {"modelValue": "Galaxy A41"},
    {"modelValue": "Galaxy M21"},
    {"modelValue": "Galaxy A11"},
    {"modelValue": "Galaxy M31"},
    {"modelValue": "Galaxy S20 Ultra 5G"},
    {"modelValue": "Galaxy S20 Ultra"},
    {"modelValue": "Galaxy S20+ 5G"},
    {"modelValue": "Galaxy S20+"},
    {"modelValue": "Galaxy S20 5G UW"},
    {"modelValue": "Galaxy S20 5G"},
    {"modelValue": "Galaxy S20"},
    {"modelValue": "Galaxy Z Flip"},
    {"modelValue": "Galaxy Tab S6 5G"},
    {"modelValue": "Galaxy Xcover Pro"},
    {"modelValue": "Galaxy Note10 Lite"},
    {"modelValue": "Galaxy S10 Lite"},
    {"modelValue": "Galaxy A01"},
    {"modelValue": "Galaxy A71"},
    {"modelValue": "Galaxy A51"},
    {"modelValue": "Galaxy Xcover FieldPro"},
    {"modelValue": "Galaxy A70s"},
    {"modelValue": "Galaxy A20s"},
    {"modelValue": "Galaxy M30s"},
    {"modelValue": "Galaxy M10s"},
    {"modelValue": "Galaxy Fold 5G"},
    {"modelValue": "Galaxy Fold"},
    {"modelValue": "Galaxy Tab Active Pro"},
    {"modelValue": "Galaxy A90 5G"},
    {"modelValue": "Galaxy A30s"},
    {"modelValue": "Galaxy A50s"},
    {"modelValue": "Galaxy Note10+ 5G"},
    {"modelValue": "Galaxy Note10+"},
    {"modelValue": "Galaxy Note10 5G"},
    {"modelValue": "Galaxy Note10"},
    {"modelValue": "Galaxy Watch Active2"},
    {"modelValue": "Galaxy Watch Active2 Aluminum"},
    {"modelValue": "Galaxy A10s"},
    {"modelValue": "Galaxy A10e"},
    {"modelValue": "Galaxy Tab S6"},
    {"modelValue": "Galaxy Tab A 8.0 (2019)"},
    {"modelValue": "Galaxy Xcover 4s"},
    {"modelValue": "Galaxy A2 Core"},
    {"modelValue": "Galaxy Watch Active"},
    {"modelValue": "Galaxy View2"},
    {"modelValue": "Galaxy S10 5G"},
    {"modelValue": "Galaxy S10+"},
    {"modelValue": "Galaxy S10"},
    {"modelValue": "Galaxy S10e"},
    {"modelValue": "Galaxy M40"},
    {"modelValue": "Galaxy M30"},
    {"modelValue": "Galaxy M20"},
    {"modelValue": "Galaxy M10"},
    {"modelValue": "Galaxy A80"},
    {"modelValue": "Galaxy A70"},
    {"modelValue": "Galaxy A60"},
    {"modelValue": "Galaxy A50"},
    {"modelValue": "Galaxy A40"},
    {"modelValue": "Galaxy A30"},
    {"modelValue": "Galaxy A20e"},
    {"modelValue": "Galaxy A20"},
    {"modelValue": "Galaxy A10"},
    {"modelValue": "Galaxy Tab S5e"},
    {"modelValue": "Galaxy Tab A 10.1 (2019)"},
    {"modelValue": "Galaxy Tab A 8.0 & S Pen (2019)"},
    {"modelValue": "Galaxy Tab Advanced2"},
    {"modelValue": "Galaxy Tab A 8.0 (2018)"},
    {"modelValue": "Galaxy Tab S4 10.5"},
    {"modelValue": "Galaxy Tab A 10.5"},
    {"modelValue": "Galaxy A8s"},
    {"modelValue": "Galaxy A6s"},
    {"modelValue": "Galaxy A9 (2018)"},
    {"modelValue": "Galaxy A7 (2018)"},
    {"modelValue": "Galaxy Note9"},
    {"modelValue": "Galaxy Watch"},
    {"modelValue": "Galaxy J6+"},
    {"modelValue": "Galaxy J4 Core"},
    {"modelValue": "Galaxy J4+"},
    {"modelValue": "Galaxy J2 Core"},
    {"modelValue": "Galaxy On6"},
    {"modelValue": "Galaxy J7 (2018)"},
    {"modelValue": "Galaxy J3 (2018)"},
    {"modelValue": "Galaxy A8 Star (A9 Star)"},
    {"modelValue": "Galaxy S Light Luxury"},
    {"modelValue": "Galaxy J8"},
    {"modelValue": "Galaxy J6"},
    {"modelValue": "Galaxy J4"},
    {"modelValue": "Galaxy A6+ (2018)"},
    {"modelValue": "Galaxy A6 (2018)"},
    {"modelValue": "Galaxy J7 Duo"},
    {"modelValue": "Galaxy J7 Prime 2"},
    {"modelValue": "Galaxy S9+"},
    {"modelValue": "Galaxy S9"},
    {"modelValue": "Galaxy J2 Pro (2018)"},
    {"modelValue": "Galaxy A8+ (2018)"},
    {"modelValue": "Galaxy A8 (2018)"},
    {"modelValue": "Galaxy J2 (2017)"},
    {"modelValue": "Galaxy Tab Active 2"},
    {"modelValue": "Galaxy Tab A 8.0 (2017)"},
    {"modelValue": "Galaxy C7 (2017)"},
    {"modelValue": "Gear Sport"},
    {"modelValue": "Galaxy Note8"},
    {"modelValue": "Galaxy S8 Active"},
    {"modelValue": "Galaxy J7 V"},
    {"modelValue": "Galaxy Note FE"},
    {"modelValue": "Galaxy J7 Max"},
    {"modelValue": "Galaxy J7 (2017)"},
    {"modelValue": "Galaxy J7 Pro"},
    {"modelValue": "Galaxy J5 (2017)"},
    {"modelValue": "Galaxy J3 (2017)"},
    {"modelValue": "Galaxy Folder2"},
    {"modelValue": "Galaxy S8"},
    {"modelValue": "Galaxy S8+"},
    {"modelValue": "Gear S3 classic LTE"},
    {"modelValue": "Galaxy C5 Pro"},
    {"modelValue": "Galaxy Xcover 4"},
    {"modelValue": "Galaxy Tab S3 9.7"},
    {"modelValue": "Galaxy J1 mini prime"},
    {"modelValue": "Galaxy J3 Emerge"},
    {"modelValue": "Galaxy C7 Pro"},
    {"modelValue": "Galaxy A7 (2017)"},
    {"modelValue": "Galaxy A5 (2017)"},
    {"modelValue": "Galaxy A3 (2017)"},
    {"modelValue": "Galaxy Grand Prime Plus"},
    {"modelValue": "Galaxy J2 Prime"},
    {"modelValue": "Galaxy C9 Pro"},
    {"modelValue": "Galaxy A8 (2016)"},
    {"modelValue": "Galaxy On8"},
    {"modelValue": "Galaxy On7 (2016)"},
    {"modelValue": "Gear S3 classic"},
    {"modelValue": "Gear S3 frontier"},
    {"modelValue": "Gear S3 frontier LTE"},
    {"modelValue": "Galaxy J5 Prime"},
    {"modelValue": "Galaxy J7 Prime"},
    {"modelValue": "Galaxy Note7 (USA)"},
    {"modelValue": "Galaxy Note7"},
    {"modelValue": "Galaxy On7 Pro"},
    {"modelValue": "Galaxy On5 Pro"},
    {"modelValue": "Galaxy Tab J"},
    {"modelValue": "Galaxy J Max"},
    {"modelValue": "Galaxy J2 Pro (2016)"},
    {"modelValue": "Galaxy J2 (2016)"},
    {"modelValue": "Z3 Corporate"},
    {"modelValue": "Galaxy Xcover 3 G389F"},
    {"modelValue": "Galaxy S7 active"},
    {"modelValue": "Galaxy J3 Pro"},
    {"modelValue": "Galaxy C7"},
    {"modelValue": "Galaxy C5"},
    {"modelValue": "Galaxy A9 Pro (2016)"},
    {"modelValue": "Galaxy J7 (2016)"},
    {"modelValue": "Galaxy J5 (2016)"},
    {"modelValue": "Galaxy Tab A 10.1 (2016)"},
    {"modelValue": "Galaxy Tab A 7.0 (2016)"},
    {"modelValue": "Galaxy S7"},
    {"modelValue": "Galaxy S7 edge"},
    {"modelValue": "Galaxy S7 edge (USA)"},
    {"modelValue": "Galaxy S7 (USA)"},
    {"modelValue": "Galaxy J1 Nxt"},
    {"modelValue": "Gear S2 classic 3G"},
    {"modelValue": "Galaxy Tab E 8.0"},
    {"modelValue": "Galaxy J1 (2016)"},
    {"modelValue": "Galaxy A9 (2016)"},
    {"modelValue": "Galaxy A7 (2016)"},
    {"modelValue": "Galaxy A5 (2016)"},
    {"modelValue": "Galaxy A3 (2016)"},
    {"modelValue": "Galaxy Express Prime"},
    {"modelValue": "Galaxy J3 (2016)"},
    {"modelValue": "Galaxy View"},
    {"modelValue": "Galaxy On7"},
    {"modelValue": "Galaxy On5"},
    {"modelValue": "Galaxy J1 Ace"},
    {"modelValue": "Gear S2 classic"},
    {"modelValue": "Gear S2"},
    {"modelValue": "Gear S2 3G"},
    {"modelValue": "Galaxy Note5 (USA)"},
    {"modelValue": "Galaxy Note5"},
    {"modelValue": "Galaxy Note5 Duos"},
    {"modelValue": "Galaxy S6 edge+ (USA)"},
    {"modelValue": "Galaxy S6 edge+"},
    {"modelValue": "Galaxy S6 edge+ Duos"},
    {"modelValue": "Galaxy S5 Neo"},
    {"modelValue": "Galaxy S4 mini I9195I"},
    {"modelValue": "Galaxy Folder"},
    {"modelValue": "Galaxy Tab S2 9.7"},
    {"modelValue": "Galaxy Tab S2 8.0"},
    {"modelValue": "Galaxy A8 Duos"},
    {"modelValue": "Galaxy A8"},
    {"modelValue": "Galaxy V Plus"},
    {"modelValue": "Galaxy J7 Nxt"},
    {"modelValue": "Galaxy J7"},
    {"modelValue": "Galaxy J5"},
    {"modelValue": "Galaxy Tab 4 10.1 (2015)"},
    {"modelValue": "Galaxy Tab E 9.6"},
    {"modelValue": "Guru Plus"},
    {"modelValue": "Metro 360"},
    {"modelValue": "Xcover 550"},
    {"modelValue": "Galaxy S6 active"},
    {"modelValue": "Galaxy Tab 3 V"},
    {"modelValue": "Galaxy Tab A 9.7 & S Pen"},
    {"modelValue": "Galaxy Tab A 9.7"},
    {"modelValue": "Galaxy Tab A 8.0 & S Pen (2015)"},
    {"modelValue": "Galaxy Tab A 8.0 (2015)"},
    {"modelValue": "Galaxy Xcover 3"},
    {"modelValue": "Galaxy S6 edge (USA)"},
    {"modelValue": "Galaxy S6 (USA)"},
    {"modelValue": "Galaxy S6 edge"},
    {"modelValue": "Galaxy S6 Duos"},
    {"modelValue": "Galaxy S6"},
    {"modelValue": "Galaxy J1 4G"},
    {"modelValue": "Galaxy J2"},
    {"modelValue": "Galaxy J1"},
    {"modelValue": "Galaxy Tab 3 Lite 7.0 VE"},
    {"modelValue": "Galaxy A7 Duos"},
    {"modelValue": "Galaxy A7"},
    {"modelValue": "Galaxy Grand Max"},
    {"modelValue": "Galaxy E7"},
    {"modelValue": "Galaxy E5"},
    {"modelValue": "Galaxy Core Prime"},
    {"modelValue": "Galaxy A5 Duos"},
    {"modelValue": "Galaxy A5"},
    {"modelValue": "Galaxy A3 Duos"},
    {"modelValue": "Galaxy A3"},
    {"modelValue": "Galaxy S5 Plus"},
    {"modelValue": "Galaxy Pocket 2"},
    {"modelValue": "Galaxy V"},
    {"modelValue": "Galaxy Grand Prime Duos TV"},
    {"modelValue": "Galaxy Grand Prime"},
    {"modelValue": "Galaxy Ace Style LTE G357"},
    {"modelValue": "Galaxy Note Edge"},
    {"modelValue": "Galaxy Note 4 Duos"},
    {"modelValue": "Galaxy Note 4 (USA)"},
    {"modelValue": "Galaxy Note 4"},
    {"modelValue": "Galaxy Tab Active LTE"},
    {"modelValue": "Galaxy Tab Active"},
    {"modelValue": "Galaxy Mega 2"},
    {"modelValue": "Gear S"},
    {"modelValue": "Gear 2 Neo"},
    {"modelValue": "Gear Live"},
    {"modelValue": "Gear 2"},
    {"modelValue": "Galaxy Gear"},
    {"modelValue": "Galaxy S5 LTE-A G901F"},
    {"modelValue": "Galaxy Alpha (S801)"},
    {"modelValue": "Galaxy Alpha"},
    {"modelValue": "Galaxy S5 mini Duos"},
    {"modelValue": "Galaxy Avant"},
    {"modelValue": "Galaxy S Duos 3"},
    {"modelValue": "Guru Music 2"},
    {"modelValue": "Metro 312"},
    {"modelValue": "Galaxy Tab 4 8.0 (2015)"},
    {"modelValue": "Galaxy Ace NXT"},
    {"modelValue": "Galaxy Star 2 Plus"},
    {"modelValue": "Galaxy S5 mini"},
    {"modelValue": "Galaxy Ace 4 LTE G313"},
    {"modelValue": "Galaxy Ace 4"},
    {"modelValue": "Galaxy Young 2"},
    {"modelValue": "Galaxy Star 2"},
    {"modelValue": "Galaxy Core II"},
    {"modelValue": "Galaxy S5 Sport"},
    {"modelValue": "Galaxy S5 LTE-A G906S"},
    {"modelValue": "Galaxy Tab S 8.4 LTE"},
    {"modelValue": "Galaxy Tab S 8.4"},
    {"modelValue": "Galaxy Tab S 10.5 LTE"},
    {"modelValue": "Galaxy Tab S 10.5"},
    {"modelValue": "Galaxy Core Lite LTE"},
    {"modelValue": "I9301I Galaxy S3 Neo"},
    {"modelValue": "Galaxy W"},
    {"modelValue": "Z"},
    {"modelValue": "Galaxy S5 Active"},
    {"modelValue": "Galaxy K zoom"},
    {"modelValue": "Galaxy Beam2"},
    {"modelValue": "I9300I Galaxy S3 Neo"},
    {"modelValue": "Galaxy Ace Style"},
    {"modelValue": "ATIV SE"},
    {"modelValue": "Galaxy Tab 4 7.0"},
    {"modelValue": "Galaxy Tab 4 7.0 3G"},
    {"modelValue": "Galaxy Tab 4 7.0 LTE"},
    {"modelValue": "Galaxy Tab 4 8.0"},
    {"modelValue": "Galaxy Tab 4 8.0 3G"},
    {"modelValue": "Galaxy Tab 4 8.0 LTE"},
    {"modelValue": "Galaxy Tab 4 10.1"},
    {"modelValue": "Galaxy Tab 4 10.1 3G"},
    {"modelValue": "Galaxy Tab 4 10.1 LTE"},
    {"modelValue": "G3812B Galaxy S3 Slim"},
    {"modelValue": "I8200 Galaxy S III mini VE"},
    {"modelValue": "Galaxy S5 Duos"},
    {"modelValue": "Galaxy S5 (octa-core)"},
    {"modelValue": "Galaxy S5 (USA)"},
    {"modelValue": "Galaxy S5"},
    {"modelValue": "Galaxy Core LTE G386W"},
    {"modelValue": "Galaxy Core LTE"},
    {"modelValue": "S5611"},
    {"modelValue": "E1272"},
    {"modelValue": "Galaxy Star Trios S5283"},
    {"modelValue": "Galaxy Note 3 Neo Duos"},
    {"modelValue": "Galaxy Note 3 Neo"},
    {"modelValue": "Galaxy Tab 3 Lite 7.0 3G"},
    {"modelValue": "Galaxy Tab 3 Lite 7.0"},
    {"modelValue": "Galaxy Grand Neo"},
    {"modelValue": "Galaxy Note Pro 12.2 LTE"},
    {"modelValue": "Galaxy Note Pro 12.2 3G"},
    {"modelValue": "Galaxy Note Pro 12.2"},
    {"modelValue": "Galaxy Tab Pro 12.2 LTE"},
    {"modelValue": "Galaxy Tab Pro 12.2 3G"},
    {"modelValue": "Galaxy Tab Pro 12.2"},
    {"modelValue": "Galaxy Tab Pro 10.1 LTE"},
    {"modelValue": "Galaxy Tab Pro 10.1"},
    {"modelValue": "Galaxy Tab Pro 8.4 3G/LTE"},
    {"modelValue": "Galaxy Tab Pro 8.4"},
    {"modelValue": "Galaxy Camera 2 GC200"},
    {"modelValue": "Galaxy Core Advance"},
    {"modelValue": "Galaxy S4 Active LTE-A"},
    {"modelValue": "Galaxy J"},
    {"modelValue": "Galaxy Win Pro G3812"},
    {"modelValue": "Galaxy S Duos 2 S7582"},
    {"modelValue": "Galaxy Grand 2"},
    {"modelValue": "I9230 Galaxy Golden"},
    {"modelValue": "C3590"},
    {"modelValue": "Galaxy Express 2"},
    {"modelValue": "I9506 Galaxy S4"},
    {"modelValue": "Galaxy Light"},
    {"modelValue": "Galaxy Round G910S"},
    {"modelValue": "Galaxy Fresh S7390"},
    {"modelValue": "Galaxy Core Plus"},
    {"modelValue": "Galaxy Fame Lite Duos S6792L"},
    {"modelValue": "Galaxy Fame Lite S6790"},
    {"modelValue": "Galaxy Star Pro S7260"},
    {"modelValue": "Galaxy Note 10.1 (2014)"},
    {"modelValue": "Galaxy Note 3"},
    {"modelValue": "Ch@t 333"},
    {"modelValue": "Galaxy Prevail 2"},
    {"modelValue": "Gravity Q T289"},
    {"modelValue": "ATIV S Neo"},
    {"modelValue": "Galaxy S4 zoom"},
    {"modelValue": "Galaxy S II TV"},
    {"modelValue": "Galaxy Ace 3"},
    {"modelValue": "I9190 Galaxy S4 mini"},
    {"modelValue": "I9295 Galaxy S4 Active"},
    {"modelValue": "Galaxy Tab 3 8.0"},
    {"modelValue": "Galaxy Tab 3 10.1 P5220"},
    {"modelValue": "Galaxy Tab 3 10.1 P5200"},
    {"modelValue": "Galaxy Tab 3 10.1 P5210"},
    {"modelValue": "Galaxy Exhibit T599"},
    {"modelValue": "Galaxy Core I8260"},
    {"modelValue": "Galaxy Tab 3 7.0 WiFi"},
    {"modelValue": "Galaxy Tab 3 7.0"},
    {"modelValue": "Galaxy Mega 6.3 I9200"},
    {"modelValue": "Galaxy Mega 5.8 I9150"},
    {"modelValue": "Galaxy Trend II Duos S7572"},
    {"modelValue": "Galaxy Win I8550"},
    {"modelValue": "Galaxy Pocket Neo S5310"},
    {"modelValue": "Galaxy Star S5280"},
    {"modelValue": "I9505 Galaxy S4"},
    {"modelValue": "I9500 Galaxy S4"},
    {"modelValue": "I9502 Galaxy S4"},
    {"modelValue": "Galaxy S4 CDMA"},
    {"modelValue": "Galaxy Note 8.0"},
    {"modelValue": "Galaxy Note 8.0 Wi-Fi"},
    {"modelValue": "Galaxy Y Plus S5303"},
    {"modelValue": "Rex 90 S5292"},
    {"modelValue": "Rex 80 S5222R"},
    {"modelValue": "Rex 70 S3802"},
    {"modelValue": "Rex 60 C3312R"},
    {"modelValue": "Metro E2202"},
    {"modelValue": "E1282T"},
    {"modelValue": "E1207T"},
    {"modelValue": "Galaxy Young S6310"},
    {"modelValue": "Galaxy Fame S6810"},
    {"modelValue": "Galaxy Express I8730"},
    {"modelValue": "S7710 Galaxy Xcover 2"},
    {"modelValue": "Ativ Odyssey I930"},
    {"modelValue": "I9105 Galaxy S II Plus"},
    {"modelValue": "Galaxy Grand I9082"},
    {"modelValue": "Galaxy Grand I9080"},
    {"modelValue": "Star Deluxe Duos S5292"},
    {"modelValue": "Galaxy Note LTE 10.1 N8020"},
    {"modelValue": "A997 Rugby III"},
    {"modelValue": "Galaxy Axiom R830"},
    {"modelValue": "Galaxy Stratosphere II I415"},
    {"modelValue": "Galaxy Discover S730M"},
    {"modelValue": "Galaxy Pop SHV-E220"},
    {"modelValue": "Galaxy Premier I9260"},
    {"modelValue": "Google Nexus 10 P8110"},
    {"modelValue": "Ativ Tab P8510"},
    {"modelValue": "Comment 2 R390C"},
    {"modelValue": "I8190 Galaxy S III mini"},
    {"modelValue": "Galaxy Music Duos S6012"},
    {"modelValue": "Galaxy Music S6010"},
    {"modelValue": "Galaxy Rugby Pro I547"},
    {"modelValue": "Galaxy Express I437"},
    {"modelValue": "Ch@t 357"},
    {"modelValue": "I9305 Galaxy S III"},
    {"modelValue": "Galaxy Victory 4G LTE L300"},
    {"modelValue": "Champ Neo Duos C3262"},
    {"modelValue": "Galaxy S Relay 4G T699"},
    {"modelValue": "Galaxy Pocket Duos S5302"},
    {"modelValue": "Galaxy Note II N7100"},
    {"modelValue": "Galaxy Note II CDMA"},
    {"modelValue": "Ativ S I8750"},
    {"modelValue": "Galaxy Camera GC100"},
    {"modelValue": "Galaxy Rush M830"},
    {"modelValue": "Galaxy Stellar 4G I200"},
    {"modelValue": "Galaxy Reverb M950"},
    {"modelValue": "Galaxy Tab 2 7.0 I705"},
    {"modelValue": "Galaxy Note 10.1 N8000"},
    {"modelValue": "Galaxy Note 10.1 N8010"},
    {"modelValue": "Array M390"},
    {"modelValue": "Galaxy S Lightray 4G R940"},
    {"modelValue": "Galaxy S Duos S7562"},
    {"modelValue": "Manhattan E3300"},
    {"modelValue": "E2262"},
    {"modelValue": "E1260B"},
    {"modelValue": "E1200 Pusha"},
    {"modelValue": "E2252"},
    {"modelValue": "Galaxy Chat B5330"},
    {"modelValue": "U485 Intensity III"},
    {"modelValue": "Galaxy I8250"},
    {"modelValue": "Galaxy Ace Advance S6800"},
    {"modelValue": "Galaxy Ace Duos S6802"},
    {"modelValue": "Galaxy Appeal I827"},
    {"modelValue": "Galaxy Tab 8.9 4G P7320T"},
    {"modelValue": "C3780"},
    {"modelValue": "C3782 Evan"},
    {"modelValue": "Galaxy Proclaim S720C"},
    {"modelValue": "I9500 Fraser"},
    {"modelValue": "Omnia M S7530"},
    {"modelValue": "Focus 2 I667"},
    {"modelValue": "Galaxy S III T999"},
    {"modelValue": "Galaxy S III I747"},
    {"modelValue": "Galaxy S III CDMA"},
    {"modelValue": "I9300 Galaxy S III"},
    {"modelValue": "E2350B"},
    {"modelValue": "U380 Brightside"},
    {"modelValue": "Galaxy Player 70 Plus"},
    {"modelValue": "Galaxy Pocket plus S5301"},
    {"modelValue": "Galaxy Pocket S5300"},
    {"modelValue": "I8530 Galaxy Beam"},
    {"modelValue": "Galaxy Tab 2 10.1 CDMA"},
    {"modelValue": "Galaxy Tab 2 10.1 P5110"},
    {"modelValue": "Galaxy Tab 2 10.1 P5100"},
    {"modelValue": "Rugby Smart I847"},
    {"modelValue": "W999"},
    {"modelValue": "Galaxy Ace II X S7560M"},
    {"modelValue": "Galaxy Ace 2 I8160"},
    {"modelValue": "Galaxy mini 2 S6500"},
    {"modelValue": "Galaxy Ace Duos I589"},
    {"modelValue": "Galaxy Pop Plus S5570i"},
    {"modelValue": "Galaxy Tab 2 7.0 P3110"},
    {"modelValue": "Galaxy Tab 2 7.0 P3100"},
    {"modelValue": "I9070 Galaxy S Advance"},
    {"modelValue": "C3312 Duos"},
    {"modelValue": "Star 3 s5220"},
    {"modelValue": "Star 3 Duos S5222"},
    {"modelValue": "Galaxy Nexus I9250M"},
    {"modelValue": "Galaxy Attain 4G"},
    {"modelValue": "Galaxy S Blaze 4G T769"},
    {"modelValue": "Galaxy Tab 7.7 LTE I815"},
    {"modelValue": "Galaxy Nexus LTE L700"},
    {"modelValue": "Exhilarate i577"},
    {"modelValue": "Galaxy S II Skyrocket HD I757"},
    {"modelValue": "Galaxy Note T879"},
    {"modelValue": "Galaxy Note I717"},
    {"modelValue": "Galaxy M Style M340S"},
    {"modelValue": "Galaxy Ace Plus S7500"},
    {"modelValue": "I929 Galaxy S II Duos"},
    {"modelValue": "Galaxy Y Duos S6102"},
    {"modelValue": "Galaxy Y Pro Duos B5512"},
    {"modelValue": "E2600"},
    {"modelValue": "M370"},
    {"modelValue": "R680 Repp"},
    {"modelValue": "I110 Illusion"},
    {"modelValue": "E1050"},
    {"modelValue": "E1232B"},
    {"modelValue": "E1230"},
    {"modelValue": "Focus S I937"},
    {"modelValue": "Focus Flash I677"},
    {"modelValue": "Galaxy S II Skyrocket i727"},
    {"modelValue": "C3330 Champ 2"},
    {"modelValue": "Exhibit II 4G T679"},
    {"modelValue": "C3350"},
    {"modelValue": "C3520"},
    {"modelValue": "Galaxy Nexus i515"},
    {"modelValue": "Galaxy Nexus I9250"},
    {"modelValue": "I9100G Galaxy S II"},
    {"modelValue": "I405 Stratosphere"},
    {"modelValue": "R730 Transfix"},
    {"modelValue": "i927 Captivate Glide"},
    {"modelValue": "DoubleTime I857"},
    {"modelValue": "M930 Transform Ultra"},
    {"modelValue": "P6210 Galaxy Tab 7.0 Plus"},
    {"modelValue": "P6200 Galaxy Tab 7.0 Plus"},
    {"modelValue": "Omnia W I8350"},
    {"modelValue": "Galaxy S II HD LTE"},
    {"modelValue": "Ch@t 527"},
    {"modelValue": "P6810 Galaxy Tab 7.7"},
    {"modelValue": "P6800 Galaxy Tab 7.7"},
    {"modelValue": "Galaxy Note N7000"},
    {"modelValue": "Galaxy S II I777"},
    {"modelValue": "Galaxy S II X T989D"},
    {"modelValue": "Galaxy S II T989"},
    {"modelValue": "Galaxy S II Epic 4G Touch"},
    {"modelValue": "S8600 Wave 3"},
    {"modelValue": "Wave M S7250"},
    {"modelValue": "Wave Y S5380"},
    {"modelValue": "Galaxy S II LTE i727R"},
    {"modelValue": "Galaxy S II LTE I9210"},
    {"modelValue": "Galaxy Tab 8.9 LTE I957"},
    {"modelValue": "Galaxy W I8150"},
    {"modelValue": "Galaxy M Pro B7800"},
    {"modelValue": "Galaxy Y Pro B5510"},
    {"modelValue": "Galaxy Y TV S5367"},
    {"modelValue": "Galaxy Y S5360"},
    {"modelValue": "Gravity TXT T379"},
    {"modelValue": "Galaxy Q T589R"},
    {"modelValue": "S5610"},
    {"modelValue": "S3770"},
    {"modelValue": "S5690 Galaxy Xcover"},
    {"modelValue": "Galaxy S II 4G I9100M"},
    {"modelValue": "I9103 Galaxy R"},
    {"modelValue": "R720 Admire"},
    {"modelValue": "Convoy 2"},
    {"modelValue": "Conquer 4G"},
    {"modelValue": "R640 Character"},
    {"modelValue": "R380 Freeform III"},
    {"modelValue": "Trender"},
    {"modelValue": "Gravity SMART"},
    {"modelValue": "Exhibit 4G"},
    {"modelValue": "E1195"},
    {"modelValue": "C414"},
    {"modelValue": "E1190"},
    {"modelValue": "C3560"},
    {"modelValue": "Dart T499"},
    {"modelValue": "C3322"},
    {"modelValue": "R260 Chrono"},
    {"modelValue": "E2232"},
    {"modelValue": "E1182"},
    {"modelValue": "I9001 Galaxy S Plus"},
    {"modelValue": "DuosTV I6712"},
    {"modelValue": "C6712 Star II DUOS"},
    {"modelValue": "Ch@t 222"},
    {"modelValue": "Ch@t 220"},
    {"modelValue": "M580 Replenish"},
    {"modelValue": "Galaxy Prevail"},
    {"modelValue": "M220L Galaxy Neo"},
    {"modelValue": "Google Nexus S I9020A"},
    {"modelValue": "Google Nexus S I9023"},
    {"modelValue": "E2230"},
    {"modelValue": "P1010 Galaxy Tab Wi-Fi"},
    {"modelValue": "P7500 Galaxy Tab 10.1 3G"},
    {"modelValue": "Galaxy Tab 10.1 LTE I905"},
    {"modelValue": "Galaxy Tab 10.1 P7510"},
    {"modelValue": "Galaxy Tab 8.9 P7300"},
    {"modelValue": "Galaxy Tab 8.9 P7310"},
    {"modelValue": "Google Nexus S 4G"},
    {"modelValue": "M260 Factor"},
    {"modelValue": "S3850 Corby II"},
    {"modelValue": "Galaxy Pro B7510"},
    {"modelValue": "I9100 Galaxy S II"},
    {"modelValue": "E2652W Champ Duos"},
    {"modelValue": "E2652 Champ Duos"},
    {"modelValue": "Galaxy S WiFi 5.0"},
    {"modelValue": "P7100 Galaxy Tab 10.1v"},
    {"modelValue": "S5780 Wave 578"},
    {"modelValue": "Ch@t 350"},
    {"modelValue": "E3213 Hero"},
    {"modelValue": "E3210"},
    {"modelValue": "E2330"},
    {"modelValue": "I9003 Galaxy SL"},
    {"modelValue": "Galaxy Ace S5830I"},
    {"modelValue": "Galaxy Ace S5830"},
    {"modelValue": "Galaxy Fit S5670"},
    {"modelValue": "Galaxy Gio S5660"},
    {"modelValue": "Galaxy Mini S5570"},
    {"modelValue": "Galaxy Pop i559"},
    {"modelValue": "Galaxy S 4G T959"},
    {"modelValue": "S5260 Star II"},
    {"modelValue": "I997 Infuse 4G"},
    {"modelValue": "R910 Galaxy Indulge"},
    {"modelValue": "Droid Charge I510"},
    {"modelValue": "Google Nexus S"},
    {"modelValue": "M190S Galaxy S Hoppin"},
    {"modelValue": "Ch@t 335"},
    {"modelValue": "C3630"},
    {"modelValue": "C3530"},
    {"modelValue": "I9010 Galaxy S Giorgio Armani"},
    {"modelValue": "A817 Solstice II"},
    {"modelValue": "A667 Evergreen"},
    {"modelValue": "E2530"},
    {"modelValue": "I100 Gem"},
    {"modelValue": "R710 Suede"},
    {"modelValue": "U750 Zeal"},
    {"modelValue": "Continuum I400"},
    {"modelValue": "Ch@t 322 Wi-Fi"},
    {"modelValue": "Ch@t 322"},
    {"modelValue": "E1252"},
    {"modelValue": "Breeze B209"},
    {"modelValue": "Hero Plus B159"},
    {"modelValue": "W169 Duos"},
    {"modelValue": "Mpower Muzik 219"},
    {"modelValue": "Mpower Txt M369"},
    {"modelValue": "Mpower TV S239"},
    {"modelValue": "E1225 Dual Sim Shift"},
    {"modelValue": "Guru E1081T"},
    {"modelValue": "Focus"},
    {"modelValue": "I8700 Omnia 7"},
    {"modelValue": "S5750 Wave575"},
    {"modelValue": "S8530 Wave II"},
    {"modelValue": "M210S Wave2"},
    {"modelValue": "Galaxy Tab T-Mobile T849"},
    {"modelValue": "P1000 Galaxy Tab"},
    {"modelValue": "Galaxy Tab CDMA P100"},
    {"modelValue": "Galaxy Tab 4G LTE"},
    {"modelValue": "T249"},
    {"modelValue": "R580 Profile"},
    {"modelValue": "R570 Messenger III"},
    {"modelValue": "I909 Galaxy S"},
    {"modelValue": "A200K Nori F"},
    {"modelValue": "A220 F Nori"},
    {"modelValue": "M130K Galaxy K"},
    {"modelValue": "Mesmerize i500"},
    {"modelValue": "M920 Transform"},
    {"modelValue": "R360 Freeform II"},
    {"modelValue": "Galaxy 551"},
    {"modelValue": "R900 Craft"},
    {"modelValue": "Xcover 271"},
    {"modelValue": "C3752"},
    {"modelValue": "C3750"},
    {"modelValue": "S7230E Wave 723"},
    {"modelValue": "M130L Galaxy U"},
    {"modelValue": "E2152"},
    {"modelValue": "S5530"},
    {"modelValue": "U360 Gusto"},
    {"modelValue": "Fascinate"},
    {"modelValue": "Vibrant"},
    {"modelValue": "A927 Flight II"},
    {"modelValue": "T669 Gravity T"},
    {"modelValue": "T479 Gravity 3"},
    {"modelValue": ":) Smiley"},
    {"modelValue": "C5010 Squash"},
    {"modelValue": "i897 Captivate"},
    {"modelValue": "B7350 Omnia PRO 4"},
    {"modelValue": "B6520 Omnia PRO 5"},
    {"modelValue": "U320 Haven"},
    {"modelValue": "U460 Intensity II"},
    {"modelValue": "M350 Seek"},
    {"modelValue": "Epic 4G"},
    {"modelValue": "Acclaim"},
    {"modelValue": "Intercept"},
    {"modelValue": "R360 Messenger Touch"},
    {"modelValue": "i225 Exec"},
    {"modelValue": "M570 Restore"},
    {"modelValue": "R351 Freeform"},
    {"modelValue": "T369"},
    {"modelValue": "S5330 Wave533"},
    {"modelValue": "S5250 Wave525"},
    {"modelValue": "I5500 Galaxy 5"},
    {"modelValue": "I5801 Galaxy Apollo"},
    {"modelValue": "I5800 Galaxy 3"},
    {"modelValue": "B7722"},
    {"modelValue": "A847 Rugby II"},
    {"modelValue": "C3300K Champ"},
    {"modelValue": "W960 AMOLED 3D"},
    {"modelValue": "M110S Galaxy S"},
    {"modelValue": "Galaxy A"},
    {"modelValue": "I9000 Galaxy S"},
    {"modelValue": "S3370"},
    {"modelValue": "I6500U Galaxy"},
    {"modelValue": "E1170"},
    {"modelValue": "Metro TV"},
    {"modelValue": "Corby TV F339"},
    {"modelValue": "S3650W Corby"},
    {"modelValue": "W9705"},
    {"modelValue": "A687 Strive"},
    {"modelValue": "A697 Sunburst"},
    {"modelValue": "S8500 Wave"},
    {"modelValue": "I8520 Galaxy Beam"},
    {"modelValue": "B3410W Ch@t"},
    {"modelValue": "M3710 Corby Beat"},
    {"modelValue": "E2370 Xcover"},
    {"modelValue": "E2550 Monte Slider"},
    {"modelValue": "C3200 Monte Bar"},
    {"modelValue": "S5620 Monte"},
    {"modelValue": "S5550 Shark 2"},
    {"modelValue": "S3550 Shark 3"},
    {"modelValue": "E1150"},
    {"modelValue": "S5350 Shark"},
    {"modelValue": "C6112"},
    {"modelValue": "M2520 Beat Techno"},
    {"modelValue": "C3510 Genoa"},
    {"modelValue": "M5650 Lindy"},
    {"modelValue": "S7070 Diva"},
    {"modelValue": "C3730C"},
    {"modelValue": "S5150 Diva folder"},
    {"modelValue": "C5130"},
    {"modelValue": "B5722"},
    {"modelValue": "M3310L"},
    {"modelValue": "M3310"},
    {"modelValue": "A897 Mythic"},
    {"modelValue": "S5500 Eco"},
    {"modelValue": "T139"},
    {"modelValue": "A797 Flight"},
    {"modelValue": "B3410"},
    {"modelValue": "M715 T*OMNIA II"},
    {"modelValue": "A886 Forever"},
    {"modelValue": "S5560 Marvel"},
    {"modelValue": "S5630C"},
    {"modelValue": "I5700 Galaxy Spica"},
    {"modelValue": "E1390"},
    {"modelValue": "E1160"},
    {"modelValue": "E2130"},
    {"modelValue": "E1130B"},
    {"modelValue": "T401G"},
    {"modelValue": "B7620 Giorgio Armani"},
    {"modelValue": "T939 Behold 2"},
    {"modelValue": "W880 AMOLED 12M"},
    {"modelValue": "Vodafone 360 H1"},
    {"modelValue": "Vodafone 360 M1"},
    {"modelValue": "B5310 CorbyPRO"},
    {"modelValue": "B3210 CorbyTXT"},
    {"modelValue": "F480i"},
    {"modelValue": "B7330 OmniaPRO"},
    {"modelValue": "E1085T"},
    {"modelValue": "E1080T"},
    {"modelValue": "S5510"},
    {"modelValue": "S5230W Star WiFi"},
    {"modelValue": "S7550 Blue Earth"},
    {"modelValue": "S3650 Corby"},
    {"modelValue": "T659 Scarlet"},
    {"modelValue": "B3310"},
    {"modelValue": "C3212"},
    {"modelValue": "U450 DoubleTake"},
    {"modelValue": "i220 Code"},
    {"modelValue": "R860 Caliber"},
    {"modelValue": "R520 Trill"},
    {"modelValue": "M900 Moment"},
    {"modelValue": "i350 Intrepid"},
    {"modelValue": "M850 Instinct HD"},
    {"modelValue": "U450 Intensity"},
    {"modelValue": "U960 Rogue"},
    {"modelValue": "S3100"},
    {"modelValue": "A887 Solstice"},
    {"modelValue": "E2120"},
    {"modelValue": "S5233T"},
    {"modelValue": "I6220 Star TV"},
    {"modelValue": "S9110"},
    {"modelValue": "T469 Gravity 2"},
    {"modelValue": "T559 Comeback"},
    {"modelValue": "T746 Impact"},
    {"modelValue": "S5600v Blade"},
    {"modelValue": "S6700"},
    {"modelValue": "C5510"},
    {"modelValue": "M2510"},
    {"modelValue": "M2310"},
    {"modelValue": "W850"},
    {"modelValue": "S8000 Jet"},
    {"modelValue": "I8000 Omnia II"},
    {"modelValue": "B7610 OmniaPRO"},
    {"modelValue": "B7320 OmniaPRO"},
    {"modelValue": "B7300 OmniaLITE"},
    {"modelValue": "M8910 Pixon12"},
    {"modelValue": "E1107 Crest Solar"},
    {"modelValue": "M2710 Beat Twist"},
    {"modelValue": "S5050"},
    {"modelValue": "T349"},
    {"modelValue": "i637 Jack"},
    {"modelValue": "S3310"},
    {"modelValue": "C3060R"},
    {"modelValue": "A167"},
    {"modelValue": "A177"},
    {"modelValue": "I7500 Galaxy"},
    {"modelValue": "J165"},
    {"modelValue": "I6210"},
    {"modelValue": "E1360"},
    {"modelValue": "E1210"},
    {"modelValue": "A657"},
    {"modelValue": "A877 Impression"},
    {"modelValue": "A257 Magnet"},
    {"modelValue": "Propel Pro"},
    {"modelValue": "B2100 Xplorer"},
    {"modelValue": "S5230 Star"},
    {"modelValue": "S5600 Preston"},
    {"modelValue": "i8910 Omnia HD"},
    {"modelValue": "S8300 UltraTOUCH"},
    {"modelValue": "M7600 Beat DJ"},
    {"modelValue": "M6710 Beat DISC"},
    {"modelValue": "S7350 Ultra s"},
    {"modelValue": "S7220 Ultra b"},
    {"modelValue": "C5220"},
    {"modelValue": "S3500"},
    {"modelValue": "S3110"},
    {"modelValue": "P250"},
    {"modelValue": "i7410"},
    {"modelValue": "T929 Memoir"},
    {"modelValue": "C3050 Stratus"},
    {"modelValue": "C3010"},
    {"modelValue": "C3110"},
    {"modelValue": "C6625"},
    {"modelValue": "E1310"},
    {"modelValue": "E1100"},
    {"modelValue": "E2210B"},
    {"modelValue": "E1125"},
    {"modelValue": "E2100B"},
    {"modelValue": "B520"},
    {"modelValue": "B5702"},
    {"modelValue": "C5212"},
    {"modelValue": "W259 Duos"},
    {"modelValue": "SCH-W699"},
    {"modelValue": "W299 Duos"},
    {"modelValue": "S9402 Ego"},
    {"modelValue": "S3030 Tobi"},
    {"modelValue": "U810 Renown"},
    {"modelValue": "i770 Saga"},
    {"modelValue": "A867 Eternity"},
    {"modelValue": "A777"},
    {"modelValue": "T919 Behold"},
    {"modelValue": "T459 Gravity"},
    {"modelValue": "E2510"},
    {"modelValue": "T219"},
    {"modelValue": "E1410"},
    {"modelValue": "T119"},
    {"modelValue": "E1117"},
    {"modelValue": "E1110"},
    {"modelValue": "C6620"},
    {"modelValue": "i907 Epix"},
    {"modelValue": "A767 Propel"},
    {"modelValue": "i7110"},
    {"modelValue": "F275"},
    {"modelValue": "F270 Beat"},
    {"modelValue": "M8800 Pixon"},
    {"modelValue": "S3600"},
    {"modelValue": "M7500 Emporio Armani"},
    {"modelValue": "M3200 Beat s"},
    {"modelValue": "T339"},
    {"modelValue": "T229"},
    {"modelValue": "A637"},
    {"modelValue": "C510"},
    {"modelValue": "A837 Rugby"},
    {"modelValue": "A237"},
    {"modelValue": "B320"},
    {"modelValue": "B210"},
    {"modelValue": "M3510 Beat b"},
    {"modelValue": "P270"},
    {"modelValue": "B2700"},
    {"modelValue": "F268"},
    {"modelValue": "T109"},
    {"modelValue": "E200 ECO"},
    {"modelValue": "D980"},
    {"modelValue": "B510"},
    {"modelValue": "E215"},
    {"modelValue": "B130"},
    {"modelValue": "i8510 INNOV8"},
    {"modelValue": "S7330"},
    {"modelValue": "i740"},
    {"modelValue": "J800 Luxe"},
    {"modelValue": "M140"},
    {"modelValue": "M130"},
    {"modelValue": "i900 Omnia"},
    {"modelValue": "U800 Soul b"},
    {"modelValue": "L870"},
    {"modelValue": "Impact sf"},
    {"modelValue": "M620"},
    {"modelValue": "B300"},
    {"modelValue": "Impact b"},
    {"modelValue": "D780"},
    {"modelValue": "V820L"},
    {"modelValue": "F110"},
    {"modelValue": "G400 Soul"},
    {"modelValue": "U900 Soul"},
    {"modelValue": "L810v Steel"},
    {"modelValue": "F480"},
    {"modelValue": "G810"},
    {"modelValue": "B200"},
    {"modelValue": "B110"},
    {"modelValue": "A827 Access"},
    {"modelValue": "P960"},
    {"modelValue": "P220"},
    {"modelValue": "P180"},
    {"modelValue": "i200"},
    {"modelValue": "F400"},
    {"modelValue": "J700"},
    {"modelValue": "J630"},
    {"modelValue": "J210"},
    {"modelValue": "J150"},
    {"modelValue": "E251"},
    {"modelValue": "L770"},
    {"modelValue": "A746"},
    {"modelValue": "A727"},
    {"modelValue": "A711"},
    {"modelValue": "A717"},
    {"modelValue": "A437"},
    {"modelValue": "A127"},
    {"modelValue": "A117"},
    {"modelValue": "SPH-i325 Ace"},
    {"modelValue": "i640"},
    {"modelValue": "L320"},
    {"modelValue": "L310"},
    {"modelValue": "L170"},
    {"modelValue": "T819"},
    {"modelValue": "F490"},
    {"modelValue": "C500"},
    {"modelValue": "Serenata"},
    {"modelValue": "D880 Duos"},
    {"modelValue": "i780"},
    {"modelValue": "i560"},
    {"modelValue": "i550"},
    {"modelValue": "F330"},
    {"modelValue": "F250"},
    {"modelValue": "i450"},
    {"modelValue": "Armani"},
    {"modelValue": "J610"},
    {"modelValue": "J400"},
    {"modelValue": "P260"},
    {"modelValue": "J750"},
    {"modelValue": "A737"},
    {"modelValue": "A517"},
    {"modelValue": "T639"},
    {"modelValue": "T509"},
    {"modelValue": "T439"},
    {"modelValue": "T429"},
    {"modelValue": "T409"},
    {"modelValue": "T739 Katalyst"},
    {"modelValue": "T729 Blast"},
    {"modelValue": "T539 Beat"},
    {"modelValue": "L600"},
    {"modelValue": "Z630"},
    {"modelValue": "M610"},
    {"modelValue": "M110"},
    {"modelValue": "B500"},
    {"modelValue": "S730i"},
    {"modelValue": "S720i"},
    {"modelValue": "J200"},
    {"modelValue": "L760"},
    {"modelValue": "F700"},
    {"modelValue": "E950"},
    {"modelValue": "F210"},
    {"modelValue": "F200"},
    {"modelValue": "i620"},
    {"modelValue": "A411"},
    {"modelValue": "ZV60"},
    {"modelValue": "Z240"},
    {"modelValue": "Z170"},
    {"modelValue": "J600"},
    {"modelValue": "i400"},
    {"modelValue": "U600"},
    {"modelValue": "U100"},
    {"modelValue": "i710"},
    {"modelValue": "i520"},
    {"modelValue": "F520"},
    {"modelValue": "F510"},
    {"modelValue": "P110"},
    {"modelValue": "E840"},
    {"modelValue": "E830"},
    {"modelValue": "E740"},
    {"modelValue": "E590"},
    {"modelValue": "E230"},
    {"modelValue": "E200"},
    {"modelValue": "C520"},
    {"modelValue": "C275"},
    {"modelValue": "C270"},
    {"modelValue": "i600"},
    {"modelValue": "i617 BlackJack II"},
    {"modelValue": "i607 BlackJack"},
    {"modelValue": "F500"},
    {"modelValue": "F300"},
    {"modelValue": "P940"},
    {"modelValue": "P930"},
    {"modelValue": "E790"},
    {"modelValue": "E490"},
    {"modelValue": "E480"},
    {"modelValue": "X540"},
    {"modelValue": "E250"},
    {"modelValue": "X520"},
    {"modelValue": "X530"},
    {"modelValue": "E690"},
    {"modelValue": "E570"},
    {"modelValue": "E420"},
    {"modelValue": "X830"},
    {"modelValue": "E890"},
    {"modelValue": "E898"},
    {"modelValue": "P310"},
    {"modelValue": "Z720"},
    {"modelValue": "Z650i"},
    {"modelValue": "Z620"},
    {"modelValue": "Z370"},
    {"modelValue": "Z360"},
    {"modelValue": "P200"},
    {"modelValue": "S501i"},
    {"modelValue": "S401i"},
    {"modelValue": "D840"},
    {"modelValue": "C400"},
    {"modelValue": "C240"},
    {"modelValue": "C180"},
    {"modelValue": "C170"},
    {"modelValue": "C160"},
    {"modelValue": "C140"},
    {"modelValue": "D830"},
    {"modelValue": "D900i"},
    {"modelValue": "X820"},
    {"modelValue": "C130"},
    {"modelValue": "E500"},
    {"modelValue": "D870"},
    {"modelValue": "D780 flip"},
    {"modelValue": "E900"},
    {"modelValue": "Z400"},
    {"modelValue": "Z550"},
    {"modelValue": "i320"},
    {"modelValue": "i310"},
    {"modelValue": "ZV50"},
    {"modelValue": "ZV40"},
    {"modelValue": "Z560"},
    {"modelValue": "P920"},
    {"modelValue": "P900"},
    {"modelValue": "P910"},
    {"modelValue": "T629"},
    {"modelValue": "D300"},
    {"modelValue": "Z600"},
    {"modelValue": "Z520"},
    {"modelValue": "Z350"},
    {"modelValue": "Z230"},
    {"modelValue": "Z330"},
    {"modelValue": "Z310"},
    {"modelValue": "Z150"},
    {"modelValue": "X680"},
    {"modelValue": "X210"},
    {"modelValue": "X160"},
    {"modelValue": "E870"},
    {"modelValue": "E780"},
    {"modelValue": "i300x"},
    {"modelValue": "D820"},
    {"modelValue": "D810"},
    {"modelValue": "D800"},
    {"modelValue": "Z540"},
    {"modelValue": "Z510"},
    {"modelValue": "E370"},
    {"modelValue": "ZV30"},
    {"modelValue": "ZV10"},
    {"modelValue": "S400i"},
    {"modelValue": "Z320i"},
    {"modelValue": "S500i"},
    {"modelValue": "Serene"},
    {"modelValue": "D600"},
    {"modelValue": "P850"},
    {"modelValue": "E730"},
    {"modelValue": "D510"},
    {"modelValue": "X670"},
    {"modelValue": "X150"},
    {"modelValue": "Z500"},
    {"modelValue": "Z130"},
    {"modelValue": "Z140"},
    {"modelValue": "D550"},
    {"modelValue": "P860"},
    {"modelValue": "Z700"},
    {"modelValue": "D730"},
    {"modelValue": "i750"},
    {"modelValue": "E760"},
    {"modelValue": "E750"},
    {"modelValue": "E720"},
    {"modelValue": "E880"},
    {"modelValue": "i300"},
    {"modelValue": "E350"},
    {"modelValue": "E640"},
    {"modelValue": "E620"},
    {"modelValue": "E340"},
    {"modelValue": "C120"},
    {"modelValue": "C210"},
    {"modelValue": "X480"},
    {"modelValue": "X140"},
    {"modelValue": "S410i"},
    {"modelValue": "S342i"},
    {"modelValue": "SCH-B100"},
    {"modelValue": "D500"},
    {"modelValue": "P730"},
    {"modelValue": "P710"},
    {"modelValue": "D428"},
    {"modelValue": "D488"},
    {"modelValue": "E630"},
    {"modelValue": "E810"},
    {"modelValue": "E800"},
    {"modelValue": "Z110"},
    {"modelValue": "D710"},
    {"modelValue": "i530"},
    {"modelValue": "i505"},
    {"modelValue": "i500"},
    {"modelValue": "i250"},
    {"modelValue": "i700"},
    {"modelValue": "X910"},
    {"modelValue": "X900"},
    {"modelValue": "X610"},
    {"modelValue": "X460"},
    {"modelValue": "X120"},
    {"modelValue": "E330"},
    {"modelValue": "E310"},
    {"modelValue": "E300"},
    {"modelValue": "C110"},
    {"modelValue": "Z107"},
    {"modelValue": "Z105"},
    {"modelValue": "E610"},
    {"modelValue": "P510"},
    {"modelValue": "E410"},
    {"modelValue": "X430"},
    {"modelValue": "P705"},
    {"modelValue": "D410"},
    {"modelValue": "E715"},
    {"modelValue": "E700"},
    {"modelValue": "D700"},
    {"modelValue": "P500"},
    {"modelValue": "E105"},
    {"modelValue": "E400"},
    {"modelValue": "D100"},
    {"modelValue": "Watch Phone"},
    {"modelValue": "P400"},
    {"modelValue": "T700"},
    {"modelValue": "S500"},
    {"modelValue": "T500"},
    {"modelValue": "S300"},
    {"modelValue": "T400"},
    {"modelValue": "T200"},
    {"modelValue": "Q300"},
    {"modelValue": "T100"},
    {"modelValue": "Q200"},
    {"modelValue": "N400"},
    {"modelValue": "Q105"},
    {"modelValue": "N300"},
    {"modelValue": "A400"},
    {"modelValue": "A300"},
    {"modelValue": "R220"},
    {"modelValue": "R210"},
    {"modelValue": "R200"},
    {"modelValue": "Q100"},
    {"modelValue": "N105"},
    {"modelValue": "A110"},
    {"modelValue": "SGH-2400"},
    {"modelValue": "SGH-2200"},
    {"modelValue": "SGH-2100"},
    {"modelValue": "SGH-810"},
    {"modelValue": "SGH-800"},
    {"modelValue": "SGH-600"},
    {"modelValue": "SGH-500"},
    {"modelValue": "SGH-250"},
    {"modelValue": "Galaxy S21"},
    {"modelValue": "Galaxy A72 5G"},
    {"modelValue": "Galaxy A91"},
    {"modelValue": "Galaxy S9 Active"},
    {"modelValue": "Galaxy On5 (2016)"},
    {"modelValue": "Galaxy J5 Prime (2017)"},
    {"modelValue": "Galaxy S7 mini"},
    {"modelValue": "Galaxy S6 Plus"},
    {"modelValue": "Galaxy Grand 3"},
    {"modelValue": "Galaxy F"},
    {"modelValue": "Galaxy Tab 3 Plus 10.1 P8220"},
    {"modelValue": "Galaxy C10"},
    {"modelValue": "Guru Dual 26"},
    {"modelValue": "C5030"},
    {"modelValue": "M8920"},
    {"modelValue": "Galaxy F14"},
    {"modelValue": "Galaxy M54"},
    {"modelValue": "Galaxy A54"},
    {"modelValue": "Galaxy A34"},
    {"modelValue": "Galaxy M14"},
    {"modelValue": "Galaxy S23 Ultra"},
    {"modelValue": "Galaxy S23+"},
    {"modelValue": "Galaxy S23"},
    {"modelValue": "Galaxy A14"},
    {"modelValue": "Galaxy A14 5G"},
    {"modelValue": "Galaxy F04"},
]


spec_iphone_14 = {
    "PhoneDetails": {
        "Brand": "Apple",
        "Name": "iphone 10",
        "Colors": "Black, White, Burgundy, Green, Graphite, Red, Blue, Purple",
    },
    "LaunchDetails": {"Date": "22 Feb 09", "Status": "Available"},
    "NetworkDetails": {"Technology": "GSM HSDPA LTE", "Band(G)": "2, 3, 4, 5"},
    "DisplayDetails": {"Type": "Amoled", "Size": "6.8 inch"},
    "BodyDetails": {"Sim": "Nano, eSIM Dual_SIM", "Stylus": "Yes"},
    "PlatformDetails": {
        "OS": "iOS 10 upgradable to iOS 14.2",
        "GPU": "Eclipse Adreono",
    },
    "Processor": {
        "Form": "Octa Core",
        "Cores1": "2.8Ghz",
        "Cores3": "2.50Ghz",
        "Cores4": "1.8Ghz",
    },
    "ChipSet": {"Type": "Exynos QulaCom SnapDragon"},
    "MemoryDetails": {
        "CardSlot": "No",
        "Internal(GB)": "128 256 512 ITB",
        "RAM(GB)": "8 12",
    },
    "MainCamera": {
        "Primary(MP)": "108",
        "Video": "8K@24fps, 4K@30/60fps, 1080p@30/60/240fps, 720p@960fps",
    },
    "SelfieCamera": {
        "Seondary(MP)": "40",
        "Video": "4K@30/60fps, 1080p@30fps",
    },
    "Battery": {
        "Type": "Li-Ion",
        "Capacity": "5000mAh",
        "Removable": "False",
        "Charging": "Wired Wireless",
    },
}
